name : push events workflow

on : push 

jobs :
  unit-testing :
    runs-on: ubuntu-latest
    
    steps :
      - name : Checkout Code
        uses : actions/checkout@v2
        
      - name : Install Package
        run  : pip install pytest numpy pandas
        
      - name : Run Test
        run  : pytest i191855_i191787_A1_MLOPS/ch08/additional_features/test_preprocessing.py 
